export const EVENTS = {
  KUBERNETES_NAMESPACE_DEPLOYMENTS_REQUEST: 'KUBERNETES_NAMESPACE_DEPLOYMENTS_REQUEST',
  KUBERNETES_EVENTS_REQUEST: 'KUBERNETES_EVENTS_REQUEST',
  KUBERNETES_POD_LOGS_REQUEST: 'KUBERNETES_POD_LOGS_REQUEST',
  DRONE_BUILD_LOGS_REQUEST: 'DRONE_BUILD_LOGS_REQUEST',
  DRONE_BUILD_FEED_REQUEST: 'DRONE_BUILD_FEED_REQUEST',
  PUBSUB_EVENTS_REQUEST: 'PUBSUB_EVENTS_REQUEST',
};
