import { EnabledPlugins } from './enabled-plugins';

export const KONG_ENABLED_PLUGINS: EnabledPlugins = [
  'jwt',
  'acl',
  'cors',
  'oauth2',
  'tcp-log',
  'udp-log',
  'file-log',
  'http-log',
  'key-auth',
  'hmac-auth',
  'basic-auth',
  'ip-restriction',
  'request-transformer',
  'response-transformer',
  'request-size-limiting',
  'rate-limiting',
  'response-ratelimiting',
  'aws-lambda',
  'bot-detection',
  'correlation-id',
  'datadog',
  'galileo',
  'ldap-auth',
  'loggly',
  'runscope',
  'statsd',
  'syslog',
];
